data:
    # name: 'coco'
    dataset: 'Coco' # 'coco'

    labels: True
    root: # datasets/COCO
    root_split_txt: # /datasets/COCO

    gaussian_label:
        enable: true
        params:
            GaussianBlur: {sigma: 0.2}


    cache_in_memory: false
    preprocessing:
        resize: [240, 320] # IGNORED in proxyopt
        # resize: [480, 640]
    augmentation:
        photometric:
            enable: false
            primitives: [
                'random_brightness', 'random_contrast', 'additive_speckle_noise',
                'additive_gaussian_noise', 'additive_shade', 'motion_blur']
            params:
                random_brightness: {max_abs_change: 50}
                random_contrast: {strength_range: [0.5, 1.5]}
                additive_gaussian_noise: {stddev_range: [0, 10]}
                additive_speckle_noise: {prob_range: [0, 0.0035]}
                additive_shade:
                    transparency_range: [-0.5, 0.5]
                    kernel_size_range: [100, 150]
                motion_blur: {max_kernel_size: 3}
        homographic:
            enable: false  # not implemented
    warped_pair:
        enable: true
        params:
            translation: false
            rotation: false
            scaling: false
            perspective: true
            scaling_amplitude: 0.00
            perspective_amplitude_x: 0.4
            perspective_amplitude_y: 0.0
            patch_ratio: 0.85
            max_angle: 1.2
            allow_artifacts: true # true
        valid_border_margin: 3
    # b - do homoadapt online, copy from magicpoint_coco_export.yaml
    homography_adaptation:
        enable: true
        num: 100 # 100
        aggregation: 'sum'
        filter_counts: 0
        homographies:
            params:
                translation: true
                rotation: true
                scaling: true
                perspective: true
                scaling_amplitude: 1.5
                perspective_amplitude_x: 0.3
                perspective_amplitude_y: 0.3
                allow_artifacts: true
                patch_ratio: 0.4

front_end_model: 'Train_model_heatmap'  # 'Train_model_frontend'

training:
    workers_train: 1 # 16
    workers_val: 1 # 2

model:
    # name: 'magic_point'
    # name: 'SuperPointNet_heatmap'
    name: 'SuperPointNet_gauss2'
    params: {
    }
    detector_loss:
        loss_type: 'softmax'


    batch_size: 1 # 32
    eval_batch_size: 1 # 32
    learning_rate: 0.0001 # 0.0001
    detection_threshold: 0.015 # 0.015
    lambda_loss: 1 # 1
    nms: 4
    dense_loss:
        enable: false
        params:
            descriptor_dist: 4 # 4, 7.5
            lambda_d: 800 # 800
    sparse_loss:
        enable: true
        params:
            num_matching_attempts: 1000
            num_masked_non_matches_per_match: 100
            lamda_d: 1
            dist: 'cos'
            method: '2d'
    other_settings: 'train 2d, gauss 0.2'
    # subpixel:
        # enable: false
        # params:
        #     subpixel_channel: 2
        # settings: 'predict flow directly'
        # loss_func: 'subpixel_loss_no_argmax' # subpixel_loss, subpixel_loss_no_argmax

proxyopt:
    config_path: '/home/boat/proxyISP/ProxyOpt/train_configs/v16.2-chroma-HumanTunedInitialHype.yaml'
    # target_images: /mnt/ssd2tb/boat/thesis/s21fe_dataset/raw/well-lit
    # target_images: /mnt/ssd2tb/boat/thesis/s21fe_dataset/raw/sunlit
    # target_images: /mnt/ssd2tb/boat/thesis/s21fe_dataset/raw_sunlit_flattest_top100
    # target_images: /mnt/ssd2tb/boat/thesis/s21fe_hpatches_v4
    # target_images: /mnt/ssd2tb/boat/thesis/robocat_singleim
    # target_images: /mnt/ssd2tb/boat/thesis/s21fe_dataset/sampled/raw/sunlit2024
    # target_images: /mnt/ssd2tb/boat/thesis/s21fe_dataset/raw
    # target_images: /mnt/ssd2tb/boat/thesis/s21fe_dataset/raw_edgeContrastIndex_top100
    # target_images: /mnt/ssd2tb/boat/thesis/s21fe_dataset/raw_bestFeatureCountThresh0.5_top100
    target_images: /mnt/ssd2tb/boat/thesis/s21fe_dataset/raw/low-light
    # target_images: /mnt/ssd2tb/boat/thesis/superpoint_dataset/HPatches_s21fe_welllitOnly
    # target_images: /home/boat/proxyISP/data/s21fe_rainbow_chart_replica
    external_homoadapt_image: # for debugging only (assume "external_image_path" contains identical image names as "target_images" with .jpeg extension )
        enable: false # must be false for actual training
        external_image_path: /mnt/ssd2tb/boat/thesis/s21fe_dataset/processed/well-lit
    cmaes:
        maxstd: 0.01
        CSA_dampfac: 10.0
    homoadapt_use_only_initial_hype: false
    homoadapt_deterministic: false
    warped_pair_homography_deterministic: false
    seed: 9999
    pooled_size: [240, 320]
    # learning_rate: 0.0005
    # learning_rate: 0.0005 # 0.0005 x gradac=8
    learning_rate: 0.005
    save_image_iter: 1
    save_training_image_iter: 1
    log_param_iter: 1
    save_hype_iter: 1
    lr_scheduler_iter: 1
    scheduler: None
    scheduler_param:
        final_lr: 0.00005
        total_steps: 5000
    # grad_ac_step: 187 # unused for cma-es
    loss:
        desc_loss: true
        det_loss: true
        det_warp_loss: true
        entropy_loss: false # experiment loss for proxyopt
        entropy_loss_beta: 1.0
        # desc_loss_lambda: 1.0
        desc_loss_lambda: 1.0

retrain: False # set true for new model
reset_iter: True # set true to set the iteration number to 0
train_iter: 200000000000 # 170000

# turn off sp val and log - BOAT
validation_interval: 200000000000 # 2000
tensorboard_interval: 2000000000000 # 200
save_interval: 20000000000000 # 2000
validation_size: 5

pretrained: 'logs/superpoint_coco_heat2_0/checkpoints/superPointNet_170000_checkpoint.pth.tar'
# pretrained: 'logs/magicpoint_synth_t2/checkpoints/superPointNet_100000_checkpoint.pth.tar'


